# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- test-azure

strategy:
  matrix:
    linux_node_8_x:
      image_name: 'ubuntu-16.04'
      node_version: 8.x
    linux_node_10_x:
      image_name: 'ubuntu-16.04'
      node_version: 10.x
    linux_node_11_x:
      image_name: 'ubuntu-16.04'
      node_version: 11.x
    macOS_node_8_x:
      image_name: 'macos-10.13'
      node_version: 8.x
    macOS_node_10_x:
      image_name: 'macos-10.13'
      node_version: 10.x
    macOS_node_11_x:
      image_name: 'macos-10.13'
      node_version: 11.x
    macOS_electron_2_x:
      image_name: 'macos-10.13'
      node_version: 8.x
      node_arch: '32'
      npm_config_runtime: 'electron'
      npm_config_target: '2.0.17'
      npm_config_disturl: 'https://atom.io/download/electron'
    win_node_8_x:
      image_name: 'vs2017-win2016'
      node_version: 8.x
    win_node_10_x:
      image_name: 'vs2017-win2016'
      node_version: 10.x
    win_node_11_x:
      image_name: 'vs2017-win2016'
      node_version: 11.x

pool:
  vmImage: $(image_name)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js $(node_version)'
- script: |
    export NODE_ARCH=$(node_arch)
    node -v
    npm i --build-from-source
