trigger:
- test-azure

variables:
  npm_config_runtime: ''
  npm_config_target: ''
  npm_config_disturl: ''

strategy:
  matrix:
    # linux_node_8_x:
    #   image_name: 'ubuntu-16.04'
    #   node_version: 8.x
    # linux_node_10_x:
    #   image_name: 'ubuntu-16.04'
    #   node_version: 10.x
    # linux_node_11_x:
    #   image_name: 'ubuntu-16.04'
    #   node_version: 11.x
    # linux_electron_2_x:
    #   image_name: 'ubuntu-16.04'
    #   node_version: 8.x
    #   npm_config_runtime: 'electron'
    #   npm_config_target: '2.0.17'
    #   npm_config_disturl: 'https://atom.io/download/electron'
    # linux_electron_4_x:
    #   image_name: 'ubuntu-16.04'
    #   node_version: 10.x
    #   npm_config_runtime: 'electron'
    #   npm_config_target: '4.0.6'
    #   npm_config_disturl: 'https://atom.io/download/electron'
    # macOS_node_8_x:
    #   image_name: 'macos-10.13'
    #   node_version: 8.x
    # macOS_node_10_x:
    #   image_name: 'macos-10.13'
    #   node_version: 10.x
    # macOS_node_11_x:
    #   image_name: 'macos-10.13'
    #   node_version: 11.x
    # macOS_electron_2_x:
    #   image_name: 'macos-10.13'
    #   node_version: 8.x
    #   npm_config_runtime: 'electron'
    #   npm_config_target: '2.0.17'
    #   npm_config_disturl: 'https://atom.io/download/electron'
    # macOS_electron_4_x:
    #   image_name: 'macos-10.13'
    #   node_version: 10.x
    #   npm_config_runtime: 'electron'
    #   npm_config_target: '4.0.6'
    #   npm_config_disturl: 'https://atom.io/download/electron'
    win64_node_8_x:
      image_name: 'vs2017-win2016'
      node_version: 8.x
    win64_node_10_x:
      image_name: 'vs2017-win2016'
      node_version: 10.x
    win64_node_11_x:
      image_name: 'vs2017-win2016'
      node_version: 11.x
    win32_node_8_x:
      image_name: 'vs2017-win2016'
      node_version: 8.15.0
      node_arch: '32'
    win32_node_10_x:
      image_name: 'vs2017-win2016'
      node_version: 10.15.0
      node_arch: '32'
    win32_node_11_x:
      image_name: 'vs2017-win2016'
      node_version: 11.7.0
      node_arch: '32'

pool:
  vmImage: $(image_name)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  condition: xor(contains(variables['image_name'], 'win'), eq(variables['node_arch'], '32'))
  displayName: 'Install Node.js $(node_version)'
- bash: |
    node -v
    npm i --build-from-source
    npm run package-prebuilt
    npm run publish-prebuilt
  env: {
    NODE_VERSION: $(node_version),
    NODE_ARCH: $(node_arch),
    npm_config_runtime: $(npm_config_runtime),
    npm_config_target: $(npm_config_target),
    npm_config_disturl: $(npm_config_disturl),
    NODE_PRE_GYP_GITHUB_TOKEN: $(chun_github_token)
  }
  condition: xor(contains(variables['image_name'], 'win'), eq(variables['node_arch'], '32'))
  displayName: 'Build'
- bash: |
    choco install -y nvm
    export PATH=$PATH:$NVM_HOME
    nvm install $(NODE_VERSION) $(NODE_ARCH)
    ls $NVM_SYMLINK
    $NVM_SYMLINK/node -v
    $NVM_SYMLINK/npm i --build-from-source
    $NVM_SYMLINK/npm run package-prebuilt
    $NVM_SYMLINK/npm run publish-prebuilt
  env: {
    NVM_HOME: "/C/ProgramData/nvm",
    NVM_SYMLINK: /C/ProgramData/nvm/v$(node_version),
    NODE_VERSION: $(node_version),
    NODE_ARCH: $(node_arch),
    npm_config_runtime: $(npm_config_runtime),
    npm_config_target: $(npm_config_target),
    npm_config_disturl: $(npm_config_disturl),
    NODE_PRE_GYP_GITHUB_TOKEN: $(chun_github_token)
  }
  condition: and(contains(variables['image_name'], 'win'), eq(variables['node_arch'], '32'))
  displayName: 'Build for Node.js $(node_version) 32-bit'
