trigger:
- test-azure

variables:
  node_8: 8.15.0
  node_10: 10.15.0
  node_11: 11.7.0
  electron_2: 2.0.17
  electron_4: 4.0.6
  npm_config_runtime: ''
  npm_config_target: ''
  npm_config_disturl: ''

strategy:
  matrix:
    linux_node_8_x:
      image_name: 'ubuntu-16.04'
      node_version: $(node_8)
    linux_node_10_x:
      image_name: 'ubuntu-16.04'
      node_version: $(node_10)
    linux_node_11_x:
      image_name: 'ubuntu-16.04'
      node_version: $(node_11)
    linux_electron_2_x:
      image_name: 'ubuntu-16.04'
      node_version: $(node_8)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_2)
      npm_config_disturl: 'https://atom.io/download/electron'
    linux_electron_4_x:
      image_name: 'ubuntu-16.04'
      node_version: $(node_10)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_4)
      npm_config_disturl: 'https://atom.io/download/electron'
    macOS_node_8_x:
      image_name: 'macos-10.13'
      node_version: $(node_8)
    macOS_node_10_x:
      image_name: 'macos-10.13'
      node_version: $(node_10)
    macOS_node_11_x:
      image_name: 'macos-10.13'
      node_version: $(node_11)
    macOS_electron_2_x:
      image_name: 'macos-10.13'
      node_version: $(node_8)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_2)
      npm_config_disturl: 'https://atom.io/download/electron'
    macOS_electron_4_x:
      image_name: 'macos-10.13'
      node_version: $(node_10)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_4)
      npm_config_disturl: 'https://atom.io/download/electron'
    win64_node_8_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_8)
    win64_node_10_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_10)
    win64_node_11_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_11)
    win64_electron_2_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_8)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_2)
      npm_config_disturl: 'https://atom.io/download/electron'
    win64_electron_4_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_10)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_4)
      npm_config_disturl: 'https://atom.io/download/electron'
    win32_node_8_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_8)
      node_arch: '32'
    win32_node_10_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_10)
      node_arch: '32'
    win32_node_11_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_11)
      node_arch: '32'
    win32_electron_2_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_8)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_2)
      npm_config_disturl: 'https://atom.io/download/electron'
      node_arch: '32'
    win32_electron_4_x:
      image_name: 'vs2017-win2016'
      node_version: $(node_10)
      npm_config_runtime: 'electron'
      npm_config_target: $(electron_4)
      npm_config_disturl: 'https://atom.io/download/electron'
      node_arch: '32'

pool:
  vmImage: $(image_name)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  condition: xor(contains(variables['image_name'], 'win'), eq(variables['node_arch'], '32'))
  displayName: 'Install Node.js $(node_version)'
- bash: |
    choco install -y nvm
    export PATH=$PATH:$NVM_HOME
    nvm install $(NODE_VERSION) $(NODE_ARCH)
    nvm use $(NODE_VERSION) $(NODE_ARCH)
    ln -sf "$NVM_SYMLINK" "$NODE_SYMLINK"
  env: {
    NVM_HOME: "/C/ProgramData/nvm",
    NVM_SYMLINK: "/C/ProgramData/nvm/v$(node_version)/node",
    NODE_SYMLINK: "/C/Program Files/nodejs/node",
    NODE_VERSION: $(node_version),
    NODE_ARCH: $(node_arch),
  }
  condition: and(contains(variables['image_name'], 'win'), eq(variables['node_arch'], '32'))
  displayName: 'Install Node.js $(node_version) 32-bit'
- bash: |
    node -v
    npm i --build-from-source
    npm run package-prebuilt
    npm run publish-prebuilt
  env: {
    NODE_VERSION: $(node_version),
    NODE_ARCH: $(node_arch),
    npm_config_runtime: $(npm_config_runtime),
    npm_config_target: $(npm_config_target),
    npm_config_disturl: $(npm_config_disturl),
    NODE_PRE_GYP_GITHUB_TOKEN: $(chun_github_token)
  }
  displayName: 'Build'
